### ISSUE TITLE
timeliness 

### ISSUE THREAD

**Issue by emmanuelmathot** [stac-extensions/product#1]
Timeliness is also a quite abstract concept that becomes specific to the mission and the related ground segment.
The value type for the `product:timeliness` should be a simple string.
For instance, under the Copernicus programme, products are released on three levels of timeliness:

- Near Real-Time (NRT): delivered less than 3 hours after data acquisition.
- Short Time-Critical (STC): delivered within 36 (Sentinel-6) to 48 (Sentinel-3) hours after data acquisition.
- Non Time-Critical (NTC): delivered typically within 1 month after data acquisition.

https://creodias.eu/cases/timeliness-and-frequency-of-sentinel-satellite-products-explained/

**Comment by m-mohr** [comment]
But why can't this be expressed as Durations so that people can search for this?
The values that providers sometimes use are non-standardized and not overly helpful, can pretty much be omitted.

**Comment by ycespb** [comment]
I agree that the values should be strings as the different categories (NRT product, consolidated product) this property indicates may be more important  than the exact number of hours (duration).  When performances improve you may also not want to have to change the "duration" value in all your metadata.  Also in https://docs.ogc.org/is/17-003r2/17-003r2.html#table_20, the consensus was to use a string for this field.

**Comment by m-mohr** [comment]
So what values could we put in the enum that people agree on?
Just using a free-text string doesn't make a lot of sense to me. Then it's not useful for search and we can just omit the field.

**Comment by emmanuelmathot** [comment]
This is very related to the ground segment product output. That is why a free text make sense to me. Then when it is used for copernicus missions, you'll have `NRT`, `NTC`, `STC` and `Nominal`

**Comment by emmanuelmathot** [comment]
Following discussions with ESA, there is a need to express both duration and codification of the timeliness since they may be not aligned across missions.
The idea is then to have another field `timeliness_code` expressing the timeliness code (e.g. NRT, STC, ...)

**Comment by m-mohr** [comment]
Sounds good to me. Can we come up with a suggested list of common values similar to processing:level for example?
Edit: In the ESA logs the field is named `product:timeliness_category`

**Comment by m-mohr** [comment]
Should be solved with https://github.com/stac-extensions/product/commit/eea5ac4ed68c58cf9e1fe54f1de95a723e083b81 and https://github.com/stac-extensions/product/commit/597fbc1158da4585176250f90d2e3dd5af307ed2

For further comments or issues please open a new issue.
