### ISSUE TITLE
erroneous link in product:acquisition_type description for Sentinel 2

### ISSUE THREAD

**Issue by dumvin** [stac-extensions/product#6]
There is a small typo in the link for Sentinel-2:
Currently it is:
> "[Annex A (page 90)] (https://sentinel.esa.int/documents/247904/2047089/Sentinel-2_Cal-Val_Phase-E2.)"
It should be 
> "[Annex A (page 90)] (https://sentinel.esa.int/documents/247904/2047089/Sentinel-2_Cal-Val_Phase-E2)"

(get rid of the space between ] and ( )

Thank you 

Vincent

**Comment by m-mohr** [comment]
Fixed, thanks.
